/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/index/index" |
       "/pages/billList/billList" |
       "/pages/login/agreement" |
       "/pages/login/changePassword" |
       "/pages/login/login" |
       "/pages/login/register" |
       "/pages/login/wxLogin" |
       "/pages/login/_wxLogin" |
       "/pages/paymentRecord/paymentRecord" |
       "/pages/recharge/recharge" |
       "/pages/rechargeRecord/rechargeRecord";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
